name: test_task
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # services
  intl_utils: ^2.8.7
  intl: ^0.19.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_screenutil: ^5.9.0
  connectivity_plus: ^5.0.2
  dart_extensions_methods: ^2.0.0

  # ui
  cupertino_icons: ^1.0.6

  # log
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1

  # state
  flutter_bloc: ^8.1.3
  provider: ^6.1.1

  # networking
  dio: ^5.4.0
  retrofit: ^4.0.3

  # navigation
  get: ^4.6.6

  # storage
  shared_preferences: ^2.2.2

  # DI & SL
  injectable: ^2.3.2
  get_it: ^7.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # icon
  flutter_launcher_icons: ^0.13.1

  # service
  build_runner: ^2.4.7
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.6.1
  retrofit_generator: ^8.0.6
  floor_generator: ^1.4.2

  # analytics
  flutter_lints: ^3.0.1

  dependency_validator: ^3.2.3

dependency_overrides:
  collection: ^1.18.0
  intl: ^0.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Text-BlackItalic.otf
          style: italic
          weight: 900
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Text-HeavyItalic.otf
          style: italic
          weight: 800
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-SemiboldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-RegularItalic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Ultralight.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-UltralightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-ThinItalic.otf
          style: italic
          weight: 100


flutter_intl:
  enabled: true
  arb_dir: assets/l10n
  output_dir: lib/core/data/utilities/l10n/generated

